# Generated by Django 5.1.3 on 2024-12-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_programmer_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=7)),
                ('token_number', models.CharField(default=None, max_length=7, null=True)),
                ('training', models.BooleanField(default=True)),
                ('entry_date', models.IntegerField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
