appname = mid_prueba
httpport = 8081
runmode = dev
autorender = false
copyrequestbody = true
EnableDocs = true
sqlconn = 

Servicio_Cartas = https://jsonplaceholder.typicode.com/posts?userId=
Servicio_Usuarios = https://jsonplaceholder.typicode.com/users/
Servicio_post = https://postman-echo.com/post
Servicio_Cartas2 = https://jsonplaceholder.typicode.com/posts/
Servicio_Subregiones = https://restcountries.com/v3.1/subregion/
Servicio_Capitales = https://restcountries.com/v3.1/capital/